Feature/oauth spotfiy v2
RomainCtl/RecoFinement-api pull request #29
Opened 2020-11-07 12:05 UTC by nitek29

2020-11-07 12:07 UTC, nitek29 commented on src/service/external_service.py
> +from src import service
to remove

2020-11-09 13:50 UTC, RomainCtl requested changes

2020-11-09 13:50 UTC, RomainCtl commented on Pipfile
> +psycopg2-binary = "*"
```suggestion
psycopg2= "*"
```

2020-11-09 13:51 UTC, RomainCtl approved these changes

2020-11-09 13:54 UTC, merged